services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - server
        networks:
            - market_place
    server:
        container_name: server
        env_file:
            - path: ./server/.env.production
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3333"
        networks:
            - market_place
        depends_on:
            - redis
        command: sh -c "node ace migration:run --force && node bin/server.js"
        restart: always
    redis:
        container_name: redis
        image: redis:7.2.5-alpine
        expose:
            - "6379"
        networks:
            - market_place
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
networks:
    market_place:
        driver: bridge
volumes:
    redis_data:
        driver: local
